# Generated by Django 6.0.1 on 2026-04-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flavors',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
